// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckServerExecutable() {
  return window['go']['main']['App']['CheckServerExecutable']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function GetBalancedLayers(arg1) {
  return window['go']['main']['App']['GetBalancedLayers'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetImageBase64(arg1) {
  return window['go']['main']['App']['GetImageBase64'](arg1);
}

export function GetSpecs() {
  return window['go']['main']['App']['GetSpecs']();
}

export function IsServerRunning() {
  return window['go']['main']['App']['IsServerRunning']();
}

export function ListClips() {
  return window['go']['main']['App']['ListClips']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function ListAvailableTools() {
  return window['go']['main']['App']['ListAvailableTools']();
}

export function SendCodeMessage(arg1) {
  return window['go']['main']['App']['SendCodeMessage'](arg1);
}

export function UpdateTodoList(arg1) {
  return window['go']['main']['App']['UpdateTodoList'](arg1);
}

export function SetCodeActive(arg1) {
  return window['go']['main']['App']['SetCodeActive'](arg1);
}
