// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckServerExecutable():Promise<boolean>;

export function ClearHistory():Promise<void>;

export function GetBalancedLayers(arg1:string):Promise<number>;

export function GetConfig():Promise<main.Config>;

export function GetFileContent(arg1:string):Promise<string>;

export function GetImageBase64(arg1:string):Promise<string>;

export function GetSpecs():Promise<main.SystemSpecs>;

export function IsServerRunning():Promise<boolean>;

export function ListClips():Promise<Array<string>>;

export function ListModels():Promise<Array<string>>;

export function SaveSettings(arg1:main.Config):Promise<string>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;
